### ISSUE TITLE
Please include a tutorial on how to install the dependencies to compile your project in Ubuntu! Thanks

### ISSUE THREAD

**Issue by roboirc** [majestrate/torrent.ano#6]

**Comment by wipedlife** [comment]
https://github.com/golang/go/wiki/Ubuntu + https://www.postgresql.org/download/linux/ubuntu/

**Comment by roboirc** [comment]
Getting error regarding: "role xxxx does not exist" where xxxx is the user name in Linux after trying to run ./indextracker. 
Please help. 
Torrent.ano doesn't seem to work.

**Comment by majestrate** [comment]
you need to set up the database

    su postgres
    psql

then type in:

     create role xxxx with login;
     create database xxxx owner xxxx;
     \q

where `xxxx` is that user name.

**Comment by roboirc** [comment]
The first two commands are not working.
They give me "Authentication Failure"

**Comment by majestrate** [comment]
run `su postgres` as root

**Comment by roboirc** [comment]
Ok thanks!

**Comment by roboirc** [comment]
Also the commands for add-category etc as in the main Readme.md are not working either. Please help!

**Comment by roboirc** [comment]
It keeps saying "Unable to find log" or "Unable to find index" or "Unable to find config.ini"
Is config.ini created by default or has to be created as an empty file first?

**Comment by majestrate** [comment]
`cp default.ini config.ini`

**Comment by majestrate** [comment]
make sure to edit the file as needed

**Comment by roboirc** [comment]
Thanks @majestrate

**Comment by roboirc** [comment]
Can the title: "TORRENTS.LIVINGSTONE.I2P" be changed or is it permanently part of the script?

**Comment by majestrate** [comment]
you can change that to whatever you want

**Comment by roboirc** [comment]
How and where?

**Comment by majestrate** [comment]
in `config.ini`

```
[index]
site-name=sitename.goes.here
```

**Comment by roboirc** [comment]
Tried that, the label TORRENTS.LIVINGSTONE.I2P is still on the tracker's main front page.

**Comment by majestrate** [comment]
do a `git pull` and then a `git reset --hard origin/master` and then rebuild.

i had to force push sorry.

**Comment by roboirc** [comment]
No problem but I can't change: "TORRENTS.LIVINGSTONE.I2P" still. Help

**Comment by majestrate** [comment]
fetch the latest revision, rebuild and restart indextracker

**Comment by majestrate** [comment]
also make sure it's running using `./indextracker config.ini` by default it uses `default.ini`

**Comment by roboirc** [comment]
Ok thanks I see it now.

**Comment by roboirc** [comment]
Thank you :)

**Comment by majestrate** [comment]
yw, can this issue be closed?

**Comment by roboirc** [comment]
Yes thanks.
