### ISSUE TITLE
build failed log heroku

### ISSUE THREAD

**Issue by todokku** [majestrate/torrent.ano#7]
-----> Go app detected

-----> Fetching jq... done

-----> Fetching stdlib.sh.v8... done

 !!    

 !!    'GOVERSION' isn't set, defaulting to 'go1.12.12'

 !!    

 !!    Run 'heroku config:set GOVERSION=goX.Y' to set the Go version to use

 !!    for future builds

 !!    

-----> New Go Version, clearing old cache

-----> Installing go1.12.12

-----> Fetching go1.12.12.linux-amd64.tar.gz... done

-----> Fetching errors-0.8.0.tar.gz... done

-----> Fetching gb-0.4.4.tar.gz... done

-----> Installing GB v0.4.4... done

-----> Running: gb build -tags heroku

FATAL: command "build" failed: failed to resolve import path "tracker": import "github.com/lib/pq": not found: stat /tmp/build_48617047ddef462eddfd9c6d1067e868/src/github.com/lib/pq: no such file or directory

 !     Push rejected, failed to compile Go app.

 !     Push faile

**Comment by majestrate** [comment]
please build using `go get github.com/majestrate/torrent.ano` and `go 1.13.x`

```
jeff@desu:~$ GOPATH=/tmp/gopath_1 go get -v github.com/majestrate/torrent.ano
github.com/majestrate/torrent.ano (download)
created GOPATH=/tmp/gopath_1; see 'go help gopath'
github.com/majestrate/torrent.ano/vendor/vendor/github.com/lib/pq/oid
github.com/majestrate/torrent.ano/vendor/tracker/log
github.com/majestrate/torrent.ano/vendor/tracker/config/parser
github.com/majestrate/torrent.ano/vendor/tracker/util
github.com/majestrate/torrent.ano/vendor/github.com/felix/go-bencode
github.com/majestrate/torrent.ano/vendor/vendor/github.com/zeebo/bencode
github.com/majestrate/torrent.ano/vendor/vendor/github.com/lib/pq
github.com/majestrate/torrent.ano/vendor/tracker/model
github.com/majestrate/torrent.ano/vendor/tracker/captcha
github.com/majestrate/torrent.ano/vendor/tracker/scrape
github.com/majestrate/torrent.ano/vendor/tracker/config
github.com/majestrate/torrent.ano/vendor/tracker/metainfo
github.com/majestrate/torrent.ano/vendor/tracker/db
github.com/majestrate/torrent.ano/vendor/tracker/feed
github.com/majestrate/torrent.ano/vendor/tracker/index
github.com/majestrate/torrent.ano/vendor/tracker
github.com/majestrate/torrent.ano
jeff@desu:~$ go version
go version go1.13.5 linux/amd64
```
